### ISSUE TITLE
Obsługa cytowania

### ISSUE THREAD

**Issue by tmurawsk** [tmurawsk/Shell-Interpreter#7]
Program powinien rozumieć cytowanie poprzez podwójne i pojedyncze cudzysłowy.

**Comment by jprokopowicz** [comment]
Kiedy nie ma spacji miedzy cudzyslowami, to licza się one oba jako 1 argument?

**Comment by tmurawsk** [comment]
Jeśli mówisz o sytuacji "a""b" to chyba jako jeden "ab". Gdy wywołałem w konsoli `touch "a""b"` to stworzyło mi jeden plik "ab".

**Comment by tmurawsk** [comment]
Good job.
